[package]
name = "rblue_core"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
bitflags = "2.6.0"
log = "0.4.21"
serde = { version = "1.0.203", features = ["derive", "alloc"] }
serde_repr = "0.1.19"
